{{- with .Values.policies.checkServiceAccount -}}
{{- if .enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-sa
  annotations:
{{- with .autogenControllers }}
    pod-policies.kyverno.io/autogen-controllers: {{ . }}
{{- end }}
    policies.kyverno.io/title: Check ServiceAccount
    policies.kyverno.io/category: Sample
    policies.kyverno.io/subject: Pod,ServiceAccount
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.21"
    policies.kyverno.io/description: >-
      ServiceAccounts with privileges to create Pods may be able to do so and name
      a ServiceAccount other than the one used to create it. This policy checks the
      Pod, if created by a ServiceAccount, and ensures the `serviceAccountName` field
      matches the actual ServiceAccount.
spec:
  validationFailureAction: {{ .validationFailureAction | default "Audit" }}
  background: false # Cannot be set to true, because variable {{`{{serviceAccountName}}`}} is not allowed
  rules:
{{- if .rulesOverride }}
{{ toYaml .rulesOverride | indent 4 }}
{{- else }}
    - name: check-sa
      match:
        any:
          - resources:
              kinds:
                - Pod
{{- if .exclude }}
      exclude: {{ toYaml .exclude | nindent 8 }}
{{- end }}
      preconditions:
        all:
          - key: "{{`{{serviceAccountName}}`}}"
            operator: Equals
            value: "*?"
      validate:
        message: "The ServiceAccount used to create this Pod is confined to using the same account when running the Pod."
        pattern:
          spec:
            serviceAccountName: "{{`{{serviceAccountName}}`}}"
{{- end }}
{{- end }}
{{- end }}
