{{- with .Values.policies.disableServiceDiscovery -}}
{{- if .enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disable-service-discovery
  annotations:
{{- with .autogenControllers }}
    pod-policies.kyverno.io/autogen-controllers: {{ . }}
{{- end }}
    policies.kyverno.io/title: Disable Service Discovery
    policies.kyverno.io/category: Other, EKS Best Practices
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.8.0-rc2
    kyverno.io/kubernetes-version: "1.24"
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Not all Pods require communicating with other Pods or resolving in-cluster Services.
      For those, disabling service discovery can increase security as the Pods are limited
      to what they can see. This policy checks which Pods set dnsPolicy to `Default` and
      enableServiceLinks to `false`, i.e. have service discovery disabled.
spec:
  validationFailureAction: {{ .validationFailureAction | default "Audit" }}
  background: {{ .background | default "true" }}
  rules:
{{- if .rulesOverride }}
{{ toYaml .rulesOverride | indent 4 }}
{{- else }}
  - name: check-dnspolicy-default
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: 'dnsPolicy should be set to Default and enableServiceLinks should be set to false'
      pattern:
        spec:
          dnsPolicy: Default
          enableServiceLinks: false
{{- end }}
{{- end }}
{{- end }}