{{- with .Values.policies.disablePodAutomountServiceAccountToken -}}
{{- if .enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disable-pod-automountserviceaccounttoken
  annotations:
{{- with .autogenControllers }}
    pod-policies.kyverno.io/autogen-controllers: {{ . }}
{{- end }}
    policies.kyverno.io/title: Disable automountServiceAccountToken
    policies.kyverno.io/category: Other, EKS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.21"
    policies.kyverno.io/description: >-
      A new ServiceAccount called `default` is created whenever a new Namespace is created.
      Pods spawned in that Namespace, unless otherwise set, will be assigned this ServiceAccount.
      This policy checks whether automountServiceAccountToken is set to false when serviceAccountName is "default" or not set.
spec:
  validationFailureAction: {{ .validationFailureAction | default "Audit" }}
  background: {{ .background | default "true" }}
  rules:
{{- if .rulesOverride }}
{{ toYaml .rulesOverride | indent 4 }}
{{- else }}
  - name: check-pod-automountserviceaccounttoken
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      all:
      - key: "{{`{{ request.object.spec.serviceAccountName || 'default' }}`}}"
        operator: Equals
        value: default
    validate:
      message: 'automountServiceAccountToken should be set to false'
      pattern:
        spec:
          automountServiceAccountToken: false
{{- end }}
{{- end }}
{{- end }}
