{{- $name := "blockStaleImages" }}
{{- $category := "other" }}
{{- $values := get .Values.policies $name }}
{{- $categoryValues := get .Values.policyCategories $category }}

{{- if or $values.enabled $categoryValues.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: block-stale-images
  annotations:
{{- with $values.autogenControllers }}
    pod-policies.kyverno.io/autogen-controllers: {{ . }}
{{- end }}
    policies.kyverno.io/title: Block Stale Images
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Images that are old usually have some open security vulnerabilities which are not patched.
      This policy checks the contents of every container image and inspects them for the create time.
      If it finds any image which was built more than 6 months ago this policy blocks the deployment.
spec:
  validationFailureAction: {{ coalesce $values.validationFailureAction $categoryValues.validationFailureAction "Audit" }}
  background: {{ coalesce $values.background $categoryValues.background "true" }}
  rules:
{{- if $values.rulesOverride }}
{{ toYaml $values.rulesOverride | indent 4 }}
{{- else }}
    - name: block-stale-images
      match:
        any:
          - resources:
              kinds:
                - Pod
{{- if $values.exclude }}
      exclude: {{ toYaml $values.exclude | nindent 8 }}
{{- end }}
      validate:
        message: "Images built more than 6 months ago are prohibited."
        foreach:
          - list: "request.object.spec.containers"
            context:
              - name: imageData
                imageRegistry:
                  reference: "{{`{{ element.image }}`}}"
            deny:
              conditions:
                all:
                  - key: "{{`{{ time_since('', '{{ imageData.configData.created }}', '') }}`}}"
                    operator: GreaterThan
                    value: {{ $values.imageAge | default "4380h" }}
{{- end }}
{{- end }}
