{{- $name := "disallowEmptyIngressHost" }}
{{- $category := "other" }}
{{- $values := get .Values.policies $name }}
{{- $categoryValues := get .Values.policyCategories $category }}

{{- if or $values.enabled $categoryValues.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-empty-ingress-host
  annotations:
{{- with $values.autogenControllers }}
    pod-policies.kyverno.io/autogen-controllers: {{ . }}
{{- end }}
    policies.kyverno.io/title: Disallow empty Ingress host
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Ingress
    policies.kyverno.io/description: >-
      An ingress resource needs to define an actual host name
      in order to be valid. This policy ensures that there is a
      hostname for each rule defined.
spec:
  validationFailureAction: {{ coalesce $values.validationFailureAction $categoryValues.validationFailureAction "Audit" }}
  background: {{ coalesce $values.background $categoryValues.background "true" }}
  rules:
{{- if $values.rulesOverride }}
{{ toYaml $values.rulesOverride | indent 4 }}
{{- else }}
    - name: disallow-empty-ingress-host
      match:
        any:
          - resources:
              kinds:
                - Ingress
{{- if $values.exclude }}
      exclude: {{ toYaml $values.exclude | nindent 8 }}
{{- end }}
      validate:
        message: "The Ingress host name must be defined, not empty."
        deny:
          conditions:
            - key: "{{`{{`}} request.object.spec.rules[].host || `[]` | length(@) {{`}}`}}"
              operator: NotEquals
              value: "{{`{{`}} request.object.spec.rules[].http || `[]` | length(@) {{`}}`}}"
{{- end }}
{{- end }}